name: workflow-lemmy-schedule

on:
  schedule:
    # run every 60 minutes
    - cron: "*/60 * * * *"

jobs:
  run-tdb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download and unpack GitHub CLI
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            cd /tmp
            curl -o './github-cli.tar.gz' -L 'https://github.com/cli/cli/releases/download/v1.10.0/gh_1.10.0_linux_amd64.tar.gz'
            tar -xvf './github-cli.tar.gz'
            sudo cp ./gh*linux_amd64/bin/gh '/usr/local/bin/'
      - name: Change directory to workspace
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            cd "${GITHUB_WORKSPACE}"
      - name: Run Trigger Docker Builds (TDB)
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            export LEMMY_USER="${{ secrets.LEMMY_USER }}"
            export LEMMY-PASSWORD="${{ secrets.LEMMY_PASSWORD }}"
            python3 ./lib/pex/lemmy.pex ./lemmy.py