name: workflow-lemmy-manual

on:
  workflow_dispatch:

jobs:
  run-tdb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Change directory to workspace
        uses: Wandalen/wretry.action@v3
        with:
          command: |
            cd "${GITHUB_WORKSPACE}"
      - name: Install requirements for Lemmy
        uses: Wandalen/wretry.action@v3
        with:
          command: |
            pip install -r ./requirements.txt
      - name: Run Lemmy
        uses: Wandalen/wretry.action@v3
        with:
          command: |
            export LEMMY_USERNAME="${{ secrets.LEMMY_USERNAME }}"
            export LEMMY_PASSWORD="${{ secrets.LEMMY_PASSWORD }}"
            python3 ./lemmy.py