name: workflow-lemmy-schedule

on:
  schedule:
    # run every 60 minutes
    - cron: "*/60 * * * *"

jobs:
  run-tdb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Change directory to workspace
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            cd "${GITHUB_WORKSPACE}"
      - name: Install requirements for Lemmy
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            export LEMMY_USERNAME="${{ secrets.LEMMY_USERNAME }}"
            export LEMMY_PASSWORD="${{ secrets.LEMMY_PASSWORD }}"
            pip install -r ./requirements.txt
      - name: Run Lemmy
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            python3 ./lemmy.py